/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.2.5 at Thu Jan 30 15:45:47 2014. */

#include "sitewhere.pb.h"



const pb_field_t sitewhere_fields[7] = {
    PB_FIELD2(  1, ENUM    , REQUIRED, STATIC  , FIRST, sitewhere, _command, _command, 0),
    PB_FIELD2(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, sitewhere, registerDevice, _command, &sitewhere__type_registerDevice_fields),
    PB_FIELD2(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, sitewhere, acknowledge, registerDevice, &sitewhere__type_acknowledge_fields),
    PB_FIELD2(  4, MESSAGE , OPTIONAL, STATIC  , OTHER, sitewhere, deviceLocation, acknowledge, &sitewhere__type_deviceLocation_fields),
    PB_FIELD2(  5, MESSAGE , OPTIONAL, STATIC  , OTHER, sitewhere, deviceAlert, deviceLocation, &sitewhere__type_deviceAlert_fields),
    PB_FIELD2(  6, MESSAGE , OPTIONAL, STATIC  , OTHER, sitewhere, deviceMeasurements, deviceAlert, &sitewhere__type_deviceMeasurements_fields),
    PB_LAST_FIELD
};

const pb_field_t sitewhere__type_registerDevice_fields[4] = {
    PB_FIELD2(  1, STRING  , REQUIRED, STATIC  , FIRST, sitewhere__type_registerDevice, hardwareId, hardwareId, 0),
    PB_FIELD2(  2, STRING  , REQUIRED, STATIC  , OTHER, sitewhere__type_registerDevice, specificationToken, hardwareId, 0),
    PB_FIELD2(  3, STRING  , OPTIONAL, STATIC  , OTHER, sitewhere__type_registerDevice, replyTo, specificationToken, 0),
    PB_LAST_FIELD
};

const pb_field_t sitewhere__type_acknowledge_fields[2] = {
    PB_FIELD2(  1, STRING  , REQUIRED, CALLBACK, FIRST, sitewhere__type_acknowledge, invocationToken, invocationToken, 0),
    PB_LAST_FIELD
};

const pb_field_t sitewhere__type_deviceLocation_fields[7] = {
    PB_FIELD2(  1, STRING  , REQUIRED, CALLBACK, FIRST, sitewhere__type_deviceLocation, hardwareId, hardwareId, 0),
    PB_FIELD2(  2, FLOAT   , REQUIRED, STATIC  , OTHER, sitewhere__type_deviceLocation, latitude, hardwareId, 0),
    PB_FIELD2(  3, FLOAT   , REQUIRED, STATIC  , OTHER, sitewhere__type_deviceLocation, longitude, latitude, 0),
    PB_FIELD2(  4, FLOAT   , OPTIONAL, STATIC  , OTHER, sitewhere__type_deviceLocation, elevation, longitude, 0),
    PB_FIELD2(  5, INT64   , OPTIONAL, STATIC  , OTHER, sitewhere__type_deviceLocation, eventDate, elevation, 0),
    PB_FIELD2(  6, STRING  , OPTIONAL, CALLBACK, OTHER, sitewhere__type_deviceLocation, invocationToken, eventDate, 0),
    PB_LAST_FIELD
};

const pb_field_t sitewhere__type_deviceAlert_fields[6] = {
    PB_FIELD2(  1, STRING  , REQUIRED, CALLBACK, FIRST, sitewhere__type_deviceAlert, hardwareId, hardwareId, 0),
    PB_FIELD2(  2, STRING  , REQUIRED, CALLBACK, OTHER, sitewhere__type_deviceAlert, type, hardwareId, 0),
    PB_FIELD2(  3, STRING  , REQUIRED, CALLBACK, OTHER, sitewhere__type_deviceAlert, message, type, 0),
    PB_FIELD2(  4, INT64   , OPTIONAL, STATIC  , OTHER, sitewhere__type_deviceAlert, eventDate, message, 0),
    PB_FIELD2(  5, STRING  , OPTIONAL, CALLBACK, OTHER, sitewhere__type_deviceAlert, invocationToken, eventDate, 0),
    PB_LAST_FIELD
};

const pb_field_t sitewhere__type_measurement_fields[3] = {
    PB_FIELD2(  1, STRING  , REQUIRED, CALLBACK, FIRST, sitewhere__type_measurement, measurementId, measurementId, 0),
    PB_FIELD2(  2, FLOAT   , REQUIRED, STATIC  , OTHER, sitewhere__type_measurement, value, measurementId, 0),
    PB_LAST_FIELD
};

const pb_field_t sitewhere__type_deviceMeasurements_fields[5] = {
    PB_FIELD2(  1, STRING  , REQUIRED, CALLBACK, FIRST, sitewhere__type_deviceMeasurements, hardwareId, hardwareId, 0),
    PB_FIELD2(  2, MESSAGE , REPEATED, CALLBACK, OTHER, sitewhere__type_deviceMeasurements, measurement, hardwareId, &sitewhere__type_measurement_fields),
    PB_FIELD2(  3, INT64   , OPTIONAL, STATIC  , OTHER, sitewhere__type_deviceMeasurements, eventDate, measurement, 0),
    PB_FIELD2(  4, STRING  , OPTIONAL, CALLBACK, OTHER, sitewhere__type_deviceMeasurements, invocationToken, eventDate, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
STATIC_ASSERT((pb_membersize(sitewhere, registerDevice) < 256 && pb_membersize(sitewhere, acknowledge) < 256 && pb_membersize(sitewhere, deviceLocation) < 256 && pb_membersize(sitewhere, deviceAlert) < 256 && pb_membersize(sitewhere, deviceMeasurements) < 256 && pb_membersize(sitewhere__type_deviceMeasurements, measurement) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_sitewhere_sitewhere__type_registerDevice_sitewhere__type_acknowledge_sitewhere__type_deviceLocation_sitewhere__type_deviceAlert_sitewhere__type_measurement_sitewhere__type_deviceMeasurements)
#endif

#if !defined(PB_FIELD_32BIT)
STATIC_ASSERT((pb_membersize(sitewhere, registerDevice) < 65536 && pb_membersize(sitewhere, acknowledge) < 65536 && pb_membersize(sitewhere, deviceLocation) < 65536 && pb_membersize(sitewhere, deviceAlert) < 65536 && pb_membersize(sitewhere, deviceMeasurements) < 65536 && pb_membersize(sitewhere__type_deviceMeasurements, measurement) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_sitewhere_sitewhere__type_registerDevice_sitewhere__type_acknowledge_sitewhere__type_deviceLocation_sitewhere__type_deviceAlert_sitewhere__type_measurement_sitewhere__type_deviceMeasurements)
#endif

