/* Automatically generated nanopb header */
/* Generated by nanopb-0.2.5 at Sun Feb 02 22:22:48 2014. */

#ifndef _PB_SITEWHERE_PB_H_
#define _PB_SITEWHERE_PB_H_
#include <pb.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _SiteWhere_Command {
    SiteWhere_Command_REGISTER = 1,
    SiteWhere_Command_ACKNOWLEDGE = 2,
    SiteWhere_Command_DEVICELOCATION = 3,
    SiteWhere_Command_DEVICEALERT = 4,
    SiteWhere_Command_DEVICEMEASUREMENTS = 5
} SiteWhere_Command;

typedef enum _Device_Command {
    Device_Command_REGISTER_ACK = 1
} Device_Command;

typedef enum _Device_RegistrationAckState {
    Device_RegistrationAckState_NEW_REGISTRATION = 1,
    Device_RegistrationAckState_ALREADY_REGISTERED = 2,
    Device_RegistrationAckState_REGISTRATION_ERROR = 3
} Device_RegistrationAckState;

typedef enum _Device_RegistrationAckError {
    Device_RegistrationAckError_INVALID_SPECIFICATION = 1,
    Device_RegistrationAckError_SITE_TOKEN_REQUIRED = 2
} Device_RegistrationAckError;

/* Struct definitions */
typedef struct _Device {
    uint8_t dummy_field;
} Device;

typedef struct _SiteWhere {
    uint8_t dummy_field;
} SiteWhere;

typedef struct _Device_Header {
    Device_Command command;
    bool has_originator;
    char originator[50];
} Device_Header;

typedef struct _Device_registrationAck {
    Device_RegistrationAckState state;
    bool has_errorType;
    Device_RegistrationAckError errorType;
    bool has_errorMessage;
    char errorMessage[75];
} Device_registrationAck;

typedef struct _SiteWhere_Acknowledge {
    char hardwareId[50];
} SiteWhere_Acknowledge;

typedef struct _SiteWhere_DeviceAlert {
    char hardwareId[50];
    char alertType[25];
    char alertMessage[75];
    bool has_eventDate;
    int64_t eventDate;
} SiteWhere_DeviceAlert;

typedef struct _SiteWhere_DeviceLocation {
    char hardwareId[50];
    float latitude;
    float longitude;
    bool has_elevation;
    float elevation;
    bool has_eventDate;
    int64_t eventDate;
} SiteWhere_DeviceLocation;

typedef struct _SiteWhere_Header {
    SiteWhere_Command command;
    bool has_originator;
    char originator[50];
} SiteWhere_Header;

typedef struct _SiteWhere_Measurement {
    char measurementId[25];
    float value;
} SiteWhere_Measurement;

typedef struct _SiteWhere_RegisterDevice {
    char hardwareId[50];
    char specificationToken[50];
    bool has_siteToken;
    char siteToken[50];
    bool has_replyTo;
    char replyTo[50];
} SiteWhere_RegisterDevice;

typedef struct _SiteWhere_DeviceMeasurements {
    char hardwareId[50];
    pb_callback_t measurement;
    bool has_eventDate;
    int64_t eventDate;
} SiteWhere_DeviceMeasurements;

/* Default values for struct fields */

/* Field tags (for use in manual encoding/decoding) */
#define Device_Header_command_tag                1
#define Device_Header_originator_tag             2
#define Device_registrationAck_state_tag         1
#define Device_registrationAck_errorType_tag     2
#define Device_registrationAck_errorMessage_tag  3
#define SiteWhere_Acknowledge_hardwareId_tag     1
#define SiteWhere_DeviceAlert_hardwareId_tag     1
#define SiteWhere_DeviceAlert_alertType_tag      2
#define SiteWhere_DeviceAlert_alertMessage_tag   3
#define SiteWhere_DeviceAlert_eventDate_tag      4
#define SiteWhere_DeviceLocation_hardwareId_tag  1
#define SiteWhere_DeviceLocation_latitude_tag    2
#define SiteWhere_DeviceLocation_longitude_tag   3
#define SiteWhere_DeviceLocation_elevation_tag   4
#define SiteWhere_DeviceLocation_eventDate_tag   5
#define SiteWhere_Header_command_tag             1
#define SiteWhere_Header_originator_tag          2
#define SiteWhere_Measurement_measurementId_tag  1
#define SiteWhere_Measurement_value_tag          2
#define SiteWhere_RegisterDevice_hardwareId_tag  1
#define SiteWhere_RegisterDevice_specificationToken_tag 2
#define SiteWhere_RegisterDevice_siteToken_tag   3
#define SiteWhere_RegisterDevice_replyTo_tag     4
#define SiteWhere_DeviceMeasurements_hardwareId_tag 1
#define SiteWhere_DeviceMeasurements_measurement_tag 2
#define SiteWhere_DeviceMeasurements_eventDate_tag 3

/* Struct field encoding specification for nanopb */
extern const pb_field_t SiteWhere_fields[1];
extern const pb_field_t SiteWhere_Header_fields[3];
extern const pb_field_t SiteWhere_RegisterDevice_fields[5];
extern const pb_field_t SiteWhere_Acknowledge_fields[2];
extern const pb_field_t SiteWhere_DeviceLocation_fields[6];
extern const pb_field_t SiteWhere_DeviceAlert_fields[5];
extern const pb_field_t SiteWhere_Measurement_fields[3];
extern const pb_field_t SiteWhere_DeviceMeasurements_fields[4];
extern const pb_field_t Device_fields[1];
extern const pb_field_t Device_Header_fields[3];
extern const pb_field_t Device_registrationAck_fields[4];

/* Maximum encoded size of messages (where known) */
#define SiteWhere_size                           0
#define SiteWhere_Header_size                    58
#define SiteWhere_RegisterDevice_size            208
#define SiteWhere_Acknowledge_size               52
#define SiteWhere_DeviceLocation_size            78
#define SiteWhere_DeviceAlert_size               167
#define SiteWhere_Measurement_size               32
#define Device_size                              0
#define Device_Header_size                       58
#define Device_registrationAck_size              89

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
