/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.7-dev at Wed Aug 31 00:57:03 2016. */

#ifndef PB_SITEWHERE_ARDUINO_PB_H_INCLUDED
#define PB_SITEWHERE_ARDUINO_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _SiteWhere_Command {
    SiteWhere_Command_SEND_REGISTRATION = 1,
    SiteWhere_Command_SEND_ACKNOWLEDGEMENT = 2,
    SiteWhere_Command_SEND_DEVICE_LOCATION = 3,
    SiteWhere_Command_SEND_DEVICE_ALERT = 4,
    SiteWhere_Command_SEND_DEVICE_MEASUREMENTS = 5,
    SiteWhere_Command_SEND_DEVICE_STREAM = 6,
    SiteWhere_Command_SEND_DEVICE_STREAM_DATA = 7,
    SiteWhere_Command_REQUEST_DEVICE_STREAM_DATA = 8
} SiteWhere_Command;
#define _SiteWhere_Command_MIN SiteWhere_Command_SEND_REGISTRATION
#define _SiteWhere_Command_MAX SiteWhere_Command_REQUEST_DEVICE_STREAM_DATA
#define _SiteWhere_Command_ARRAYSIZE ((SiteWhere_Command)(SiteWhere_Command_REQUEST_DEVICE_STREAM_DATA+1))

typedef enum _Device_Command {
    Device_Command_ACK_REGISTRATION = 1,
    Device_Command_ACK_DEVICE_STREAM = 2,
    Device_Command_RECEIVE_DEVICE_STREAM_DATA = 3
} Device_Command;
#define _Device_Command_MIN Device_Command_ACK_REGISTRATION
#define _Device_Command_MAX Device_Command_RECEIVE_DEVICE_STREAM_DATA
#define _Device_Command_ARRAYSIZE ((Device_Command)(Device_Command_RECEIVE_DEVICE_STREAM_DATA+1))

typedef enum _Device_RegistrationAckState {
    Device_RegistrationAckState_NEW_REGISTRATION = 1,
    Device_RegistrationAckState_ALREADY_REGISTERED = 2,
    Device_RegistrationAckState_REGISTRATION_ERROR = 3
} Device_RegistrationAckState;
#define _Device_RegistrationAckState_MIN Device_RegistrationAckState_NEW_REGISTRATION
#define _Device_RegistrationAckState_MAX Device_RegistrationAckState_REGISTRATION_ERROR
#define _Device_RegistrationAckState_ARRAYSIZE ((Device_RegistrationAckState)(Device_RegistrationAckState_REGISTRATION_ERROR+1))

typedef enum _Device_RegistrationAckError {
    Device_RegistrationAckError_INVALID_SPECIFICATION = 1,
    Device_RegistrationAckError_SITE_TOKEN_REQUIRED = 2,
    Device_RegistrationAckError_NEW_DEVICES_NOT_ALLOWED = 3
} Device_RegistrationAckError;
#define _Device_RegistrationAckError_MIN Device_RegistrationAckError_INVALID_SPECIFICATION
#define _Device_RegistrationAckError_MAX Device_RegistrationAckError_NEW_DEVICES_NOT_ALLOWED
#define _Device_RegistrationAckError_ARRAYSIZE ((Device_RegistrationAckError)(Device_RegistrationAckError_NEW_DEVICES_NOT_ALLOWED+1))

typedef enum _Device_DeviceStreamAckState {
    Device_DeviceStreamAckState_STREAM_CREATED = 1,
    Device_DeviceStreamAckState_STREAM_EXISTS = 2,
    Device_DeviceStreamAckState_STREAM_FAILED = 3
} Device_DeviceStreamAckState;
#define _Device_DeviceStreamAckState_MIN Device_DeviceStreamAckState_STREAM_CREATED
#define _Device_DeviceStreamAckState_MAX Device_DeviceStreamAckState_STREAM_FAILED
#define _Device_DeviceStreamAckState_ARRAYSIZE ((Device_DeviceStreamAckState)(Device_DeviceStreamAckState_STREAM_FAILED+1))

/* Struct definitions */
typedef struct _Device {
    char dummy_field;
/* @@protoc_insertion_point(struct:Device) */
} Device;

typedef struct _Model {
    char dummy_field;
/* @@protoc_insertion_point(struct:Model) */
} Model;

typedef struct _SiteWhere {
    char dummy_field;
/* @@protoc_insertion_point(struct:SiteWhere) */
} SiteWhere;

typedef struct _Device_DeviceStreamAck {
    char streamId[40];
    Device_DeviceStreamAckState state;
/* @@protoc_insertion_point(struct:Device_DeviceStreamAck) */
} Device_DeviceStreamAck;

typedef struct _Device_Header {
    Device_Command command;
    bool has_originator;
    char originator[30];
    bool has_nestedPath;
    char nestedPath[50];
    bool has_nestedSpec;
    char nestedSpec[40];
/* @@protoc_insertion_point(struct:Device_Header) */
} Device_Header;

typedef struct _Device_RegistrationAck {
    Device_RegistrationAckState state;
    bool has_errorType;
    Device_RegistrationAckError errorType;
    bool has_errorMessage;
    char errorMessage[70];
/* @@protoc_insertion_point(struct:Device_RegistrationAck) */
} Device_RegistrationAck;

typedef struct _Model_Measurement {
    char measurementId[30];
    uint64_t measurementValue;
/* @@protoc_insertion_point(struct:Model_Measurement) */
} Model_Measurement;

typedef struct _Model_Metadata {
    char name[30];
    char value[30];
/* @@protoc_insertion_point(struct:Model_Metadata) */
} Model_Metadata;

typedef struct _SiteWhere_Acknowledge {
    char hardwareId[40];
    bool has_message;
    char message[70];
/* @@protoc_insertion_point(struct:SiteWhere_Acknowledge) */
} SiteWhere_Acknowledge;

typedef struct _SiteWhere_DeviceStreamDataRequest {
    char hardwareId[40];
    char streamId[40];
    uint64_t sequenceNumber;
/* @@protoc_insertion_point(struct:SiteWhere_DeviceStreamDataRequest) */
} SiteWhere_DeviceStreamDataRequest;

typedef struct _SiteWhere_Header {
    SiteWhere_Command command;
    bool has_originator;
    char originator[30];
/* @@protoc_insertion_point(struct:SiteWhere_Header) */
} SiteWhere_Header;

typedef struct _SiteWhere_RegisterDevice {
    char hardwareId[40];
    char specificationToken[40];
    pb_callback_t metadata;
    bool has_siteToken;
    char siteToken[40];
/* @@protoc_insertion_point(struct:SiteWhere_RegisterDevice) */
} SiteWhere_RegisterDevice;

typedef struct _Model_DeviceAlert {
    char hardwareId[40];
    char alertType[40];
    char alertMessage[70];
    bool has_eventDate;
    uint64_t eventDate;
    pb_size_t metadata_count;
    Model_Metadata metadata[3];
/* @@protoc_insertion_point(struct:Model_DeviceAlert) */
} Model_DeviceAlert;

typedef struct _Model_DeviceLocation {
    char hardwareId[40];
    uint64_t latitude;
    uint64_t longitude;
    bool has_elevation;
    uint64_t elevation;
    bool has_eventDate;
    uint64_t eventDate;
    pb_size_t metadata_count;
    Model_Metadata metadata[3];
/* @@protoc_insertion_point(struct:Model_DeviceLocation) */
} Model_DeviceLocation;

typedef struct _Model_DeviceMeasurements {
    char hardwareId[40];
    pb_size_t measurement_count;
    Model_Measurement measurement[5];
    bool has_eventDate;
    uint64_t eventDate;
    pb_size_t metadata_count;
    Model_Metadata metadata[3];
/* @@protoc_insertion_point(struct:Model_DeviceMeasurements) */
} Model_DeviceMeasurements;

typedef struct _Model_DeviceStream {
    char hardwareId[40];
    char streamId[40];
    char contentType[40];
    pb_size_t metadata_count;
    Model_Metadata metadata[3];
/* @@protoc_insertion_point(struct:Model_DeviceStream) */
} Model_DeviceStream;

typedef struct _Model_DeviceStreamData {
    char hardwareId[40];
    char streamId[40];
    uint64_t sequenceNumber;
    pb_callback_t data;
    bool has_eventDate;
    uint64_t eventDate;
    pb_size_t metadata_count;
    Model_Metadata metadata[3];
/* @@protoc_insertion_point(struct:Model_DeviceStreamData) */
} Model_DeviceStreamData;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Model_init_default                       {0}
#define Model_Metadata_init_default              {"", ""}
#define Model_DeviceLocation_init_default        {"", 0, 0, false, 0, false, 0, 0, {Model_Metadata_init_default, Model_Metadata_init_default, Model_Metadata_init_default}}
#define Model_DeviceAlert_init_default           {"", "", "", false, 0, 0, {Model_Metadata_init_default, Model_Metadata_init_default, Model_Metadata_init_default}}
#define Model_Measurement_init_default           {"", 0}
#define Model_DeviceMeasurements_init_default    {"", 0, {Model_Measurement_init_default, Model_Measurement_init_default, Model_Measurement_init_default, Model_Measurement_init_default, Model_Measurement_init_default}, false, 0, 0, {Model_Metadata_init_default, Model_Metadata_init_default, Model_Metadata_init_default}}
#define Model_DeviceStream_init_default          {"", "", "", 0, {Model_Metadata_init_default, Model_Metadata_init_default, Model_Metadata_init_default}}
#define Model_DeviceStreamData_init_default      {"", "", 0, {{NULL}, NULL}, false, 0, 0, {Model_Metadata_init_default, Model_Metadata_init_default, Model_Metadata_init_default}}
#define SiteWhere_init_default                   {0}
#define SiteWhere_Header_init_default            {(SiteWhere_Command)0, false, ""}
#define SiteWhere_RegisterDevice_init_default    {"", "", {{NULL}, NULL}, false, ""}
#define SiteWhere_Acknowledge_init_default       {"", false, ""}
#define SiteWhere_DeviceStreamDataRequest_init_default {"", "", 0}
#define Device_init_default                      {0}
#define Device_Header_init_default               {(Device_Command)0, false, "", false, "", false, ""}
#define Device_RegistrationAck_init_default      {(Device_RegistrationAckState)0, false, (Device_RegistrationAckError)0, false, ""}
#define Device_DeviceStreamAck_init_default      {"", (Device_DeviceStreamAckState)0}
#define Model_init_zero                          {0}
#define Model_Metadata_init_zero                 {"", ""}
#define Model_DeviceLocation_init_zero           {"", 0, 0, false, 0, false, 0, 0, {Model_Metadata_init_zero, Model_Metadata_init_zero, Model_Metadata_init_zero}}
#define Model_DeviceAlert_init_zero              {"", "", "", false, 0, 0, {Model_Metadata_init_zero, Model_Metadata_init_zero, Model_Metadata_init_zero}}
#define Model_Measurement_init_zero              {"", 0}
#define Model_DeviceMeasurements_init_zero       {"", 0, {Model_Measurement_init_zero, Model_Measurement_init_zero, Model_Measurement_init_zero, Model_Measurement_init_zero, Model_Measurement_init_zero}, false, 0, 0, {Model_Metadata_init_zero, Model_Metadata_init_zero, Model_Metadata_init_zero}}
#define Model_DeviceStream_init_zero             {"", "", "", 0, {Model_Metadata_init_zero, Model_Metadata_init_zero, Model_Metadata_init_zero}}
#define Model_DeviceStreamData_init_zero         {"", "", 0, {{NULL}, NULL}, false, 0, 0, {Model_Metadata_init_zero, Model_Metadata_init_zero, Model_Metadata_init_zero}}
#define SiteWhere_init_zero                      {0}
#define SiteWhere_Header_init_zero               {(SiteWhere_Command)0, false, ""}
#define SiteWhere_RegisterDevice_init_zero       {"", "", {{NULL}, NULL}, false, ""}
#define SiteWhere_Acknowledge_init_zero          {"", false, ""}
#define SiteWhere_DeviceStreamDataRequest_init_zero {"", "", 0}
#define Device_init_zero                         {0}
#define Device_Header_init_zero                  {(Device_Command)0, false, "", false, "", false, ""}
#define Device_RegistrationAck_init_zero         {(Device_RegistrationAckState)0, false, (Device_RegistrationAckError)0, false, ""}
#define Device_DeviceStreamAck_init_zero         {"", (Device_DeviceStreamAckState)0}

/* Field tags (for use in manual encoding/decoding) */
#define Device_DeviceStreamAck_streamId_tag      1
#define Device_DeviceStreamAck_state_tag         2
#define Device_Header_command_tag                1
#define Device_Header_originator_tag             2
#define Device_Header_nestedPath_tag             3
#define Device_Header_nestedSpec_tag             4
#define Device_RegistrationAck_state_tag         1
#define Device_RegistrationAck_errorType_tag     2
#define Device_RegistrationAck_errorMessage_tag  3
#define Model_Measurement_measurementId_tag      1
#define Model_Measurement_measurementValue_tag   2
#define Model_Metadata_name_tag                  1
#define Model_Metadata_value_tag                 2
#define SiteWhere_Acknowledge_hardwareId_tag     1
#define SiteWhere_Acknowledge_message_tag        2
#define SiteWhere_DeviceStreamDataRequest_hardwareId_tag 1
#define SiteWhere_DeviceStreamDataRequest_streamId_tag 2
#define SiteWhere_DeviceStreamDataRequest_sequenceNumber_tag 3
#define SiteWhere_Header_command_tag             1
#define SiteWhere_Header_originator_tag          2
#define SiteWhere_RegisterDevice_hardwareId_tag  1
#define SiteWhere_RegisterDevice_specificationToken_tag 2
#define SiteWhere_RegisterDevice_metadata_tag    3
#define SiteWhere_RegisterDevice_siteToken_tag   4
#define Model_DeviceAlert_hardwareId_tag         1
#define Model_DeviceAlert_alertType_tag          2
#define Model_DeviceAlert_alertMessage_tag       3
#define Model_DeviceAlert_eventDate_tag          4
#define Model_DeviceAlert_metadata_tag           5
#define Model_DeviceLocation_hardwareId_tag      1
#define Model_DeviceLocation_latitude_tag        2
#define Model_DeviceLocation_longitude_tag       3
#define Model_DeviceLocation_elevation_tag       4
#define Model_DeviceLocation_eventDate_tag       5
#define Model_DeviceLocation_metadata_tag        6
#define Model_DeviceMeasurements_hardwareId_tag  1
#define Model_DeviceMeasurements_measurement_tag 2
#define Model_DeviceMeasurements_eventDate_tag   3
#define Model_DeviceMeasurements_metadata_tag    4
#define Model_DeviceStream_hardwareId_tag        1
#define Model_DeviceStream_streamId_tag          2
#define Model_DeviceStream_contentType_tag       3
#define Model_DeviceStream_metadata_tag          4
#define Model_DeviceStreamData_hardwareId_tag    1
#define Model_DeviceStreamData_streamId_tag      2
#define Model_DeviceStreamData_sequenceNumber_tag 3
#define Model_DeviceStreamData_data_tag          4
#define Model_DeviceStreamData_eventDate_tag     5
#define Model_DeviceStreamData_metadata_tag      6

/* Struct field encoding specification for nanopb */
extern const pb_field_t Model_fields[1];
extern const pb_field_t Model_Metadata_fields[3];
extern const pb_field_t Model_DeviceLocation_fields[7];
extern const pb_field_t Model_DeviceAlert_fields[6];
extern const pb_field_t Model_Measurement_fields[3];
extern const pb_field_t Model_DeviceMeasurements_fields[5];
extern const pb_field_t Model_DeviceStream_fields[5];
extern const pb_field_t Model_DeviceStreamData_fields[7];
extern const pb_field_t SiteWhere_fields[1];
extern const pb_field_t SiteWhere_Header_fields[3];
extern const pb_field_t SiteWhere_RegisterDevice_fields[5];
extern const pb_field_t SiteWhere_Acknowledge_fields[3];
extern const pb_field_t SiteWhere_DeviceStreamDataRequest_fields[4];
extern const pb_field_t Device_fields[1];
extern const pb_field_t Device_Header_fields[5];
extern const pb_field_t Device_RegistrationAck_fields[4];
extern const pb_field_t Device_DeviceStreamAck_fields[3];

/* Maximum encoded size of messages (where known) */
#define Model_size                               0
#define Model_Metadata_size                      64
#define Model_DeviceLocation_size                276
#define Model_DeviceAlert_size                   363
#define Model_Measurement_size                   41
#define Model_DeviceMeasurements_size            464
#define Model_DeviceStream_size                  324
/* Model_DeviceStreamData_size depends on runtime parameters */
#define SiteWhere_size                           0
#define SiteWhere_Header_size                    34
/* SiteWhere_RegisterDevice_size depends on runtime parameters */
#define SiteWhere_Acknowledge_size               114
#define SiteWhere_DeviceStreamDataRequest_size   93
#define Device_size                              0
#define Device_Header_size                       128
#define Device_RegistrationAck_size              76
#define Device_DeviceStreamAck_size              44

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define SITEWHERE_ARDUINO_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
