/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.2.5 at Wed Feb 19 18:48:59 2014. */

#include "uno.h"



const pb_field_t Uno_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t Uno__Header_fields[3] = {
    PB_FIELD2(  1, ENUM    , REQUIRED, STATIC  , FIRST, Uno__Header, command, command, 0),
    PB_FIELD2(  2, STRING  , OPTIONAL, STATIC  , OTHER, Uno__Header, originator, command, 0),
    PB_LAST_FIELD
};

const pb_field_t Uno_ping_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t Uno_testEvents_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t Uno_pinMode_fields[3] = {
    PB_FIELD2(  1, INT32   , REQUIRED, STATIC  , FIRST, Uno_pinMode, pinNumber, pinNumber, 0),
    PB_FIELD2(  2, BOOL    , REQUIRED, STATIC  , OTHER, Uno_pinMode, output, pinNumber, 0),
    PB_LAST_FIELD
};

const pb_field_t Uno_digitalRead_fields[2] = {
    PB_FIELD2(  1, INT32   , REQUIRED, STATIC  , FIRST, Uno_digitalRead, pinNumber, pinNumber, 0),
    PB_LAST_FIELD
};

const pb_field_t Uno_digitalWrite_fields[3] = {
    PB_FIELD2(  1, INT32   , REQUIRED, STATIC  , FIRST, Uno_digitalWrite, pinNumber, pinNumber, 0),
    PB_FIELD2(  2, BOOL    , REQUIRED, STATIC  , OTHER, Uno_digitalWrite, value, pinNumber, 0),
    PB_LAST_FIELD
};

const pb_field_t Uno_analogRead_fields[2] = {
    PB_FIELD2(  1, INT32   , REQUIRED, STATIC  , FIRST, Uno_analogRead, pinNumber, pinNumber, 0),
    PB_LAST_FIELD
};

const pb_field_t Uno_serialPrintln_fields[2] = {
    PB_FIELD2(  1, STRING  , REQUIRED, STATIC  , FIRST, Uno_serialPrintln, message, message, 0),
    PB_LAST_FIELD
};


