/* Automatically generated nanopb header */
/* Generated by nanopb-0.2.5 at Wed Feb 19 18:48:59 2014. */

#ifndef _PB_UNO_PB_H_
#define _PB_UNO_PB_H_
#include <pb.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _Uno_Command {
    Uno_Command_PING = 1,
    Uno_Command_TESTEVENTS = 2,
    Uno_Command_PINMODE = 3,
    Uno_Command_DIGITALREAD = 4,
    Uno_Command_DIGITALWRITE = 5,
    Uno_Command_ANALOGREAD = 6,
    Uno_Command_SERIALPRINTLN = 7
} Uno_Command;

/* Struct definitions */
typedef struct _Uno {
    uint8_t dummy_field;
} Uno;

typedef struct _Uno_ping {
    uint8_t dummy_field;
} Uno_ping;

typedef struct _Uno_testEvents {
    uint8_t dummy_field;
} Uno_testEvents;

typedef struct _Uno__Header {
    Uno_Command command;
    bool has_originator;
    char originator[30];
} Uno__Header;

typedef struct _Uno_analogRead {
    int32_t pinNumber;
} Uno_analogRead;

typedef struct _Uno_digitalRead {
    int32_t pinNumber;
} Uno_digitalRead;

typedef struct _Uno_digitalWrite {
    int32_t pinNumber;
    bool value;
} Uno_digitalWrite;

typedef struct _Uno_pinMode {
    int32_t pinNumber;
    bool output;
} Uno_pinMode;

typedef struct _Uno_serialPrintln {
    char message[70];
} Uno_serialPrintln;

/* Default values for struct fields */

/* Field tags (for use in manual encoding/decoding) */
#define Uno__Header_command_tag                  1
#define Uno__Header_originator_tag               2
#define Uno_analogRead_pinNumber_tag             1
#define Uno_digitalRead_pinNumber_tag            1
#define Uno_digitalWrite_pinNumber_tag           1
#define Uno_digitalWrite_value_tag               2
#define Uno_pinMode_pinNumber_tag                1
#define Uno_pinMode_output_tag                   2
#define Uno_serialPrintln_message_tag            1

/* Struct field encoding specification for nanopb */
extern const pb_field_t Uno_fields[1];
extern const pb_field_t Uno__Header_fields[3];
extern const pb_field_t Uno_ping_fields[1];
extern const pb_field_t Uno_testEvents_fields[1];
extern const pb_field_t Uno_pinMode_fields[3];
extern const pb_field_t Uno_digitalRead_fields[2];
extern const pb_field_t Uno_digitalWrite_fields[3];
extern const pb_field_t Uno_analogRead_fields[2];
extern const pb_field_t Uno_serialPrintln_fields[2];

/* Maximum encoded size of messages (where known) */
#define Uno_size                                 0
#define Uno__Header_size                         38
#define Uno_ping_size                            0
#define Uno_testEvents_size                      0
#define Uno_pinMode_size                         13
#define Uno_digitalRead_size                     11
#define Uno_digitalWrite_size                    13
#define Uno_analogRead_size                      11
#define Uno_serialPrintln_size                   72

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
