/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6 at Tue Sep 27 10:29:54 2016. */

#ifndef PB_CUSTOM_PB_H_INCLUDED
#define PB_CUSTOM_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _ArduinoCustom_Command {
    ArduinoCustom_Command_SERIALPRINTLN = 1,
    ArduinoCustom_Command_PING = 2,
    ArduinoCustom_Command_TESTEVENTS = 3
} ArduinoCustom_Command;
#define _ArduinoCustom_Command_MIN ArduinoCustom_Command_SERIALPRINTLN
#define _ArduinoCustom_Command_MAX ArduinoCustom_Command_TESTEVENTS
#define _ArduinoCustom_Command_ARRAYSIZE ((ArduinoCustom_Command)(ArduinoCustom_Command_TESTEVENTS+1))

/* Struct definitions */
typedef struct _ArduinoCustom {
    char dummy_field;
/* @@protoc_insertion_point(struct:ArduinoCustom) */
} ArduinoCustom;

typedef struct _ArduinoCustom_ping {
    char dummy_field;
/* @@protoc_insertion_point(struct:ArduinoCustom_ping) */
} ArduinoCustom_ping;

typedef struct _ArduinoCustom_testEvents {
    char dummy_field;
/* @@protoc_insertion_point(struct:ArduinoCustom_testEvents) */
} ArduinoCustom_testEvents;

typedef struct _ArduinoCustom__Header {
    ArduinoCustom_Command command;
    bool has_originator;
    char originator[30];
    pb_callback_t nestedPath;
    pb_callback_t nestedSpec;
/* @@protoc_insertion_point(struct:ArduinoCustom__Header) */
} ArduinoCustom__Header;

typedef struct _ArduinoCustom_serialPrintln {
    char message[100];
/* @@protoc_insertion_point(struct:ArduinoCustom_serialPrintln) */
} ArduinoCustom_serialPrintln;

/* Default values for struct fields */

/* Initializer values for message structs */
#define ArduinoCustom_init_default               {0}
#define ArduinoCustom__Header_init_default       {(ArduinoCustom_Command)0, false, "", {{NULL}, NULL}, {{NULL}, NULL}}
#define ArduinoCustom_serialPrintln_init_default {""}
#define ArduinoCustom_ping_init_default          {0}
#define ArduinoCustom_testEvents_init_default    {0}
#define ArduinoCustom_init_zero                  {0}
#define ArduinoCustom__Header_init_zero          {(ArduinoCustom_Command)0, false, "", {{NULL}, NULL}, {{NULL}, NULL}}
#define ArduinoCustom_serialPrintln_init_zero    {""}
#define ArduinoCustom_ping_init_zero             {0}
#define ArduinoCustom_testEvents_init_zero       {0}

/* Field tags (for use in manual encoding/decoding) */
#define ArduinoCustom__Header_command_tag        1
#define ArduinoCustom__Header_originator_tag     2
#define ArduinoCustom__Header_nestedPath_tag     3
#define ArduinoCustom__Header_nestedSpec_tag     4
#define ArduinoCustom_serialPrintln_message_tag  1

/* Struct field encoding specification for nanopb */
extern const pb_field_t ArduinoCustom_fields[1];
extern const pb_field_t ArduinoCustom__Header_fields[5];
extern const pb_field_t ArduinoCustom_serialPrintln_fields[2];
extern const pb_field_t ArduinoCustom_ping_fields[1];
extern const pb_field_t ArduinoCustom_testEvents_fields[1];

/* Maximum encoded size of messages (where known) */
#define ArduinoCustom_size                       0
/* ArduinoCustom__Header_size depends on runtime parameters */
#define ArduinoCustom_serialPrintln_size         102
#define ArduinoCustom_ping_size                  0
#define ArduinoCustom_testEvents_size            0

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define CUSTOM_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
